let content = document.querySelector('.js-generated.content')
let header = document.createElement('h1')
header.setAttribute('class', 'dog-name')
header.append('Rizzo')
content.append(header)

let image = document.querySelector('.js-generated.content')
let photo = document.createElement('image')
header.setAttribute('class', 'dog-image')
header.append('Rizzo')
content.append(image)